In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame([ ['green', 'L', 10.1, 'yes'], ['green', 'M', 13.5, 'no'], ['red', 'XL', 15.3, 'yes'], ['blue', 'S', 12.7, 'yes']
])
df.columns = ['color', 'size', 'price', 'label']

In [3]:
df

color size  price label
0  green    L   10.1   yes
1  green    M   13.5    no
2    red   XL   15.3   yes
3   blue    S   12.7   yes

In [6]:
y = df['label'] #pandas Series 객체

In [7]:
y1 = np.where(y=='no', 0, 1)

In [8]:
y1

array([1, 0, 1, 1])

In [9]:
d = {'no':0, 'yes':1}
y2 = y.map(d).to_numpy()

In [10]:
y2

array([1, 0, 1, 1], dtype=int64)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
encoder = LabelEncoder()
encoder.fit(y)

LabelEncoder()

In [13]:
encoder.classes_

array(['no', 'yes'], dtype=object)

In [14]:
y3 = encoder.transform(y)

In [15]:
y3

array([1, 0, 1, 1])

In [19]:
X = df.drop('label', axis=1)
X

color size  price
0  green    L   10.1
1  green    M   13.5
2    red   XL   15.3
3   blue    S   12.7

In [21]:
size_mapping = {'XS':0, 'S':1, 'M':2, 'L':3, 'XL':4}
X['size'] = X['size'].map(size_mapping)

In [22]:
X

color  size  price
0  green     3   10.1
1  green     2   13.5
2    red     4   15.3
3   blue     1   12.7

In [23]:
X_dummy = pd.get_dummies(X)

In [24]:
X_dummy

size  price  color_blue  color_green  color_red
0     3   10.1           0            1          0
1     2   13.5           0            1          0
2     4   15.3           0            0          1
3     1   12.7           1            0          0

In [25]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
wine = pd.read_csv(path, header=None)

In [26]:
wine

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [58]:
y = wine.iloc[:, 0].to_numpy()
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [60]:
X = wine.iloc[:, 1:].to_numpy()
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [63]:
from sklearn.preprocessing import StandardScaler

In [66]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_std = scaler.transform(X_train)

In [67]:
pd.DataFrame(X_train_std).describe()

0             1             2             3             4   \
count  1.240000e+02  1.240000e+02  1.240000e+02  1.240000e+02  1.240000e+02   
mean   6.890098e-15  1.683241e-16  3.799660e-15  2.856138e-16 -3.178461e-16   
std    1.004057e+00  1.004057e+00  1.004057e+00  1.004057e+00  1.004057e+00   
min   -1.971837e+00 -1.380243e+00 -2.554934e+00 -2.525252e+00 -2.069521e+00   
25%   -8.150037e-01 -6.275963e-01 -5.499141e-01 -6.917901e-01 -7.889079e-01   
50%    3.819870e-02 -4.351583e-01 -5.565323e-02 -9.065504e-02 -1.130290e-01   
75%    8.033481e-01  6.980880e-01  7.370293e-01  5.705935e-01  5.094911e-01   
max    2.181832e+00  2.947475e+00  3.152379e+00  3.065304e+00  3.693237e+00   

                 5             6             7             8             9   \
count  1.240000e+02  1.240000e+02  1.240000e+02  1.240000e+02  1.240000e+02   
mean   1.662649e-15  1.598184e-16 -1.198862e-15  1.888274e-15 -1.615195e-15   
std    1.004057e+00  1.004057e+00  1.004057e+00  1.004057e+00  1.004057e+00   
min   -2.187238e+00 -1.691226e+00 -1.964528e+00 -2.068907e+00 -1.419256e+00   
25%   -8.535947e-01 -7.985839e-01 -8.092365e-01 -6.496852e-01 -8.006399e-01   
50%    1.385058e-01  9.896271e-02 -2.315907e-01 -7.775997e-02 -1.438903e-01   
75%    8.297234e-01  8.322044e-01  6.142478e-01  5.619490e-01  4.704883e-01   
max    2.529306e+00  2.958360e+00  2.161513e+00  3.286008e+00  3.351712e+00   

                 10            11            12  
count  1.240000e+02  1.240000e+02  1.240000e+02  
mean  -5.783904e-16  8.631089e-16 -1.334058e-16  
std    1.004057e+00  1.004057e+00  1.004057e+00  
min   -2.147813e+00 -1.947267e+00 -1.465378e+00  
25%   -7.436984e-01 -8.974047e-01 -7.823560e-01  
50%    4.894675e-02  2.823374e-01 -2.499217e-01  
75%    7.510038e-01  7.946413e-01  8.610452e-01  
max    2.109824e+00  1.992422e+00  2.843268e+00

In [68]:
X_test_std = scaler.transform(X_test)

In [70]:
pd.DataFrame(X_test).describe()

0          1          2          3           4          5   \
count  54.000000  54.000000  54.000000  54.000000   54.000000  54.000000   
mean   12.925000   2.296296   2.324259  18.790741  101.240741   2.226852   
std     0.778808   0.983454   0.283912   3.259255   14.687866   0.645591   
min    11.030000   0.900000   1.360000  10.600000   81.000000   1.100000   
25%    12.362500   1.602500   2.200000  16.100000   89.000000   1.700000   
50%    12.905000   1.885000   2.315000  18.750000   98.000000   2.215000   
75%    13.500000   3.020000   2.507500  21.375000  110.750000   2.637500   
max    14.390000   4.610000   2.920000  27.000000  162.000000   3.850000   

              6          7          8          9          10         11  \
count  54.000000  54.000000  54.000000  54.000000  54.000000  54.000000   
mean    1.949259   0.347593   1.476111   4.985741   0.964926   2.594074   
std     0.944004   0.130658   0.509940   2.215631   0.245672   0.748045   
min     0.470000   0.170000   0.410000   1.280000   0.540000   1.290000   
25%     1.117500   0.252500   1.142500   3.255000   0.780000   1.830000   
50%     2.060000   0.295000   1.460000   4.600000   0.985000   2.755000   
75%     2.740000   0.430000   1.800000   6.250000   1.127500   3.275000   
max     3.750000   0.660000   3.280000  10.680000   1.710000   3.920000   

                12  
count    54.000000  
mean    728.685185  
std     288.053836  
min     315.000000  
25%     505.000000  
50%     670.000000  
75%     883.750000  
max    1480.000000

In [71]:
from sklearn.decomposition import PCA

In [72]:
pca = PCA(n_components=2)

In [73]:
pca.fit(X_train_std)

PCA(n_components=2)

In [75]:
X_train_pca = pca.transform(X_train_std)

In [76]:
X_train_pca.shape

(124, 2)

In [77]:
pca.components_

array([[-0.13724218,  0.24724326, -0.02545159,  0.20694508, -0.15436582,
        -0.39376952, -0.41735106,  0.30572896, -0.30668347,  0.07554066,
        -0.32613263, -0.36861022, -0.29669651],
       [ 0.50303478,  0.16487119,  0.24456476, -0.11352904,  0.28974518,
         0.05080104, -0.02287338,  0.09048885,  0.00835233,  0.54977581,
        -0.20716433, -0.24902536,  0.38022942]])

In [78]:
pca.explained_variance_ratio_

array([0.36951469, 0.18434927])