In [1]:
import numpy as np

In [20]:
a = np.array([2, 6, 3, 7, 8.]) # 숫자가 하나만 float여도 전부가 float형이 됨.

In [14]:
a

array([2., 6., 3., 7., 8.])

In [15]:
print(a)

[2. 6. 3. 7. 8.]


In [16]:
type(a)

numpy.ndarray

In [17]:
a.ndim # 차원의 갯수

1

In [18]:
a.shape # 차원의 크기

(5,)

In [19]:
a.dtype

dtype('float64')

In [21]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b.ndim

2

In [24]:
b.shape

(2, 3)

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.full((2, 3), 3.141592)

array([[3.141592, 3.141592, 3.141592],
       [3.141592, 3.141592, 3.141592]])

In [32]:
np.arange(1, 10, 2) # 시작, 끝, 간격

array([1, 3, 5, 7, 9])

In [33]:
np.linspace(0, 1, 5) # 등차수열을 만들어 줌. 시작, 끝, 나누는 갯수

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.random.random() # 전부 0~1 사이의 난수 추출

0.5941683517307828

In [35]:
np.random.seed(1)

In [36]:
np.random.random()

0.417022004702574

In [38]:
np.random.random((3,3)) # (2,2)는 0.00014394817

array([[7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01],
       [3.45560727e-01, 3.96767474e-01, 5.38816734e-01]])

In [40]:
np.random.normal(0, 1, (2, 3)) # 시작, 끝, (행, 열)

array([[ 1.74481176, -0.7612069 ,  0.3190391 ],
       [-0.24937038,  1.46210794, -2.06014071]])

In [44]:
np.random.randint(1, 7, 10) # 시작, 끝, 나타낼 갯수

array([6, 4, 3, 2, 1, 4, 6, 2, 2, 4])

In [46]:
x = np.array([5, 2, 9, 3, 7])

In [47]:
y = np.array([[2, 4, 6], [1, 3, 5]])

In [48]:
x

array([5, 2, 9, 3, 7])

In [49]:
y

array([[2, 4, 6],
       [1, 3, 5]])

In [50]:
x[2]

9

In [51]:
y[1, 1]

3

In [52]:
x[1:4] # 1<= y < 4

array([2, 9, 3])

In [53]:
x[1:]

array([2, 9, 3, 7])

In [54]:
x[:2]

array([5, 2])

In [55]:
x[:]

array([5, 2, 9, 3, 7])

In [56]:
x[::2]

array([5, 9, 7])

In [57]:
y

array([[2, 4, 6],
       [1, 3, 5]])

In [58]:
y[1:2, 1:]

array([[3, 5]])

In [59]:
y[0, :]

array([2, 4, 6])

In [60]:
z = y[:, 1]

In [61]:
z

array([4, 3])

In [62]:
z[1] = 10000

In [63]:
z

array([    4, 10000])

In [64]:
y

array([[    2,     4,     6],
       [    1, 10000,     5]])

In [69]:
a = np.arange(9).reshape((3,3))

In [70]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
a.shape

(3, 3)

In [76]:
b = np.arange(5).reshape((5, 1))
b.shape

(5, 1)

In [77]:
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [78]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [81]:
a.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [83]:
a = np.array([1, 2, 3]); b = np.array([4, 5, 6])

In [84]:
a + b # numpy에서는 + 의 경우 원소의 합으로 사용됨

array([5, 7, 9])

In [89]:
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [90]:
grid1 = np.ones((3,3))

In [91]:
grid1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
grid2 = np.full((3, 3), 2.)

In [96]:
grid2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [99]:
np.concatenate([grid1, grid2]) # 행 별로 붙음, axis=0 이 default 값

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [100]:
np.concatenate([grid1, grid2], axis=1) # 열 별로 붙음

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

In [101]:
x = np.arange(3, 15, 2)

In [102]:
x

array([ 3,  5,  7,  9, 11, 13])

In [109]:
a, b, c = np.split(x, [2, 5])

In [110]:
a

array([3, 5])

In [111]:
b

array([ 7,  9, 11])

In [112]:
c

array([13])