In [1]:
import tensorflow as tf

In [2]:
t = tf.convert_to_tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [4]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
t_float = tf.cast(t, dtype=tf.float32)

In [6]:
t_float

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [7]:
ds = tf.data.Dataset.from_tensor_slices([5, 2, 7, 9, 3])

In [8]:
ds

<TensorSliceDataset shapes: (), types: tf.int32>

In [9]:
for ex in ds:
3    print(ex)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [10]:
#지도학습 : 특성행렬, 레이블 벡터

In [11]:
#두 개의 데이터셋을 하나의 데이터셋으로 연결하기 : X에 Y 붙이기
X = tf.data.Dataset.from_tensor_slices([[1, 2, 3], [9, 9, 9]])

In [12]:
y = tf.data.Dataset.from_tensor_slices([0, 1, 0])

In [13]:
my_ds = tf.data.Dataset.zip((X, y))

In [14]:
my_ds

<ZipDataset shapes: ((3,), ()), types: (tf.int32, tf.int32)>

In [15]:
for ex in my_ds:
    print(ex)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([9, 9, 9])>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)


In [17]:
for ex in my_ds:
    print(ex[0].numpy(), ex[1].numpy())

[1 2 3] 0
[9 9 9] 1
