In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data'
df = pd.read_csv(path, header=None)

In [3]:
df

0  1      2      3       4       5        6        7        8   \
0      842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [9]:
X = df.iloc[:, 2:].values

In [10]:
y = df.iloc[:, 1]

In [11]:
y = np.where(y=='M', 1, 0)

<이진 분류>
* positive class : 더 심각하거나 중요한 클래스, M ==> 1
* negative class : B ==> 0

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 1)

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

In [16]:
from sklearn.pipeline import make_pipeline

In [18]:
pipe = make_pipeline(StandardScaler(),
                     PCA(n_components=2),
                     LogisticRegression(random_state=1))

In [20]:
type(pipe)

sklearn.pipeline.Pipeline

In [22]:
pipe.fit(X_train, y_train) # pipeline 안에 표준화가 포함되어 있기 때문에 X_train_std 해 줄 필요 없음

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('pca', PCA(n_components=2)),
                ('logisticregression', LogisticRegression(random_state=1))])

In [23]:
y_pred = pipe.predict(X_test)

In [24]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1])

In [25]:
y_test

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1])

In [26]:
pipe.score(X_test, y_test)

0.956140350877193

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
confusion_matrix(y_test, y_pred) # confusion_matrix(실제값(행), 예측값(열))

array([[71,  1],
       [ 4, 38]], dtype=int64)

In [29]:
from sklearn.model_selection import cross_val_score

In [31]:
scores = cross_val_score(estimator=pipe,
               X=X_train, y=y_train,
               cv=10, n_jobs=-1)

In [33]:
scores

array([0.93478261, 0.93478261, 0.95652174, 0.95652174, 0.93478261,
       0.95555556, 0.97777778, 0.93333333, 0.95555556, 0.95555556])

In [34]:
np.mean(scores)

0.9495169082125603

In [40]:
from sklearn.tree import DecisionTreeClassifier

In [61]:
best_score=0
for k in range(1, 11):
    scores = cross_val_score(estimator=DecisionTreeClassifier(max_depth=k, random_state=1),
                             X=X_train, y=y_train, cv=5, n_jobs=-1)
    val_score = np.mean(scores)
    print('max_depth : ', k, val_score)
    if val_score > best_score:
        best_score = val_score
        best_param = {'max_depth':k}

max_depth :  1 0.8813186813186814
max_depth :  2 0.9318681318681319
max_depth :  3 0.9296703296703297
max_depth :  4 0.9406593406593406
max_depth :  5 0.9384615384615385
max_depth :  6 0.9362637362637363
max_depth :  7 0.9406593406593406
max_depth :  8 0.9406593406593406
max_depth :  9 0.9406593406593406
max_depth :  10 0.9406593406593406


In [62]:
best_score

0.9406593406593406

In [63]:
best_param

{'max_depth': 4}

In [64]:
best_tree = DecisionTreeClassifier(**best_param)

In [67]:
best_tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4)

In [68]:
best_tree.score(X_test, y_test)

0.9122807017543859

In [69]:
from sklearn.model_selection import GridSearchCV

In [70]:
my_grid = {'max_depth':range(1, 11)}

In [71]:
gs = GridSearchCV(estimator=DecisionTreeClassifier(random_state=1),
                 param_grid= my_grid,
                 cv = 5, n_jobs=-1)

In [72]:
gs.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=1), n_jobs=-1,
             param_grid={'max_depth': range(1, 11)})

In [73]:
gs.best_score_

0.9406593406593406

In [74]:
gs.best_params_

{'max_depth': 4}

In [75]:
from sklearn.svm import SVC
pipe_svc = make_pipeline(StandardScaler(), SVC(kernel='rbf', random_state=1))
p_list = [0.001,0.01,0.1,1.0,10.0,100.0]
param_grid = {'svc__C':p_list, 'svc__gamma':p_list}
gs = GridSearchCV(estimator=pipe_svc, param_grid=param_grid, scoring='accuracy', cv=5, n_jobs=-1)
gs.fit(X_train, y_train)
print(gs.best_params_) #{'svc__C': 10.0, 'svc__gamma': 0.01}
print(gs.score(X_test, y_test)) #0.9739

{'svc__C': 10.0, 'svc__gamma': 0.01}
0.9736842105263158
